# TCL File Generated by Component Editor 13.0sp1
# Sat Nov 14 23:07:25 PKT 2020
# DO NOT MODIFY


# 
# RISCV_CORE "RISCV_CORE" v1.0
# Ammaz Anwar 2020.11.14.23:07:25
# RISC V 32 bit Processor
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module RISCV_CORE
# 
set_module_property DESCRIPTION "RISC V 32 bit Processor"
set_module_property NAME RISCV_CORE
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Own IP"
set_module_property AUTHOR "Ammaz Anwar"
set_module_property DISPLAY_NAME RISCV_CORE
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL RV32_core
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ALU.v VERILOG PATH ../Core-files/ALU.v
add_fileset_file BRANCH_COMP.v VERILOG PATH ../Core-files/BRANCH_COMP.v
add_fileset_file CONTROL_UNIT.v VERILOG PATH ../Core-files/CONTROL_UNIT.v
add_fileset_file DATA_MEM.v VERILOG PATH ../Core-files/DATA_MEM.v
add_fileset_file dmem.hex HEX PATH ../Core-files/dmem.hex
add_fileset_file Forwarding.v VERILOG PATH ../Core-files/Forwarding.v
add_fileset_file imem.hex HEX PATH ../Core-files/imem.hex
add_fileset_file IMM_GEN.v VERILOG PATH ../Core-files/IMM_GEN.v
add_fileset_file INSTRUCTION_MEM.v VERILOG PATH ../Core-files/INSTRUCTION_MEM.v
add_fileset_file MAC_UNIT.v VERILOG PATH ../Core-files/MAC_UNIT.v
add_fileset_file MUX2X1.v VERILOG PATH ../Core-files/MUX2X1.v
add_fileset_file PCSel_compute.v VERILOG PATH ../Core-files/PCSel_compute.v
add_fileset_file PIPES.v VERILOG PATH ../Core-files/PIPES.v
add_fileset_file PROGRAM_COUNTER.v VERILOG PATH ../Core-files/PROGRAM_COUNTER.v
add_fileset_file REG_FILE.v VERILOG PATH ../Core-files/REG_FILE.v
add_fileset_file RISC_V.v VERILOG PATH ../Core-files/RISC_V.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL RV32_core
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ALU.v VERILOG PATH ../Core-files/ALU.v
add_fileset_file BRANCH_COMP.v VERILOG PATH ../Core-files/BRANCH_COMP.v
add_fileset_file CONTROL_UNIT.v VERILOG PATH ../Core-files/CONTROL_UNIT.v
add_fileset_file DATA_MEM.v VERILOG PATH ../Core-files/DATA_MEM.v
add_fileset_file dmem.hex HEX PATH ../Core-files/dmem.hex
add_fileset_file Forwarding.v VERILOG PATH ../Core-files/Forwarding.v
add_fileset_file imem.hex HEX PATH ../Core-files/imem.hex
add_fileset_file IMM_GEN.v VERILOG PATH ../Core-files/IMM_GEN.v
add_fileset_file INSTRUCTION_MEM.v VERILOG PATH ../Core-files/INSTRUCTION_MEM.v
add_fileset_file MAC_UNIT.v VERILOG PATH ../Core-files/MAC_UNIT.v
add_fileset_file MUX2X1.v VERILOG PATH ../Core-files/MUX2X1.v
add_fileset_file PCSel_compute.v VERILOG PATH ../Core-files/PCSel_compute.v
add_fileset_file PIPES.v VERILOG PATH ../Core-files/PIPES.v
add_fileset_file PROGRAM_COUNTER.v VERILOG PATH ../Core-files/PROGRAM_COUNTER.v
add_fileset_file REG_FILE.v VERILOG PATH ../Core-files/REG_FILE.v
add_fileset_file RISC_V.v VERILOG PATH ../Core-files/RISC_V.v


# 
# parameters
# 
add_parameter DATA_W INTEGER 32
set_parameter_property DATA_W DEFAULT_VALUE 32
set_parameter_property DATA_W DISPLAY_NAME DATA_W
set_parameter_property DATA_W TYPE INTEGER
set_parameter_property DATA_W ENABLED false
set_parameter_property DATA_W UNITS None
set_parameter_property DATA_W HDL_PARAMETER true
add_parameter ALU_SEL_W INTEGER 4
set_parameter_property ALU_SEL_W DEFAULT_VALUE 4
set_parameter_property ALU_SEL_W DISPLAY_NAME ALU_SEL_W
set_parameter_property ALU_SEL_W TYPE INTEGER
set_parameter_property ALU_SEL_W ENABLED false
set_parameter_property ALU_SEL_W UNITS None
set_parameter_property ALU_SEL_W HDL_PARAMETER true
add_parameter ADDR_W INTEGER 5
set_parameter_property ADDR_W DEFAULT_VALUE 5
set_parameter_property ADDR_W DISPLAY_NAME ADDR_W
set_parameter_property ADDR_W TYPE INTEGER
set_parameter_property ADDR_W ENABLED false
set_parameter_property ADDR_W UNITS None
set_parameter_property ADDR_W HDL_PARAMETER true
add_parameter DMEM_ADDR_W INTEGER 12
set_parameter_property DMEM_ADDR_W DEFAULT_VALUE 12
set_parameter_property DMEM_ADDR_W DISPLAY_NAME DMEM_ADDR_W
set_parameter_property DMEM_ADDR_W TYPE INTEGER
set_parameter_property DMEM_ADDR_W ENABLED false
set_parameter_property DMEM_ADDR_W UNITS None
set_parameter_property DMEM_ADDR_W HDL_PARAMETER true
add_parameter INST_W INTEGER 32
set_parameter_property INST_W DEFAULT_VALUE 32
set_parameter_property INST_W DISPLAY_NAME INST_W
set_parameter_property INST_W TYPE INTEGER
set_parameter_property INST_W ENABLED false
set_parameter_property INST_W UNITS None
set_parameter_property INST_W HDL_PARAMETER true
add_parameter ADDR_W_IMEM INTEGER 12
set_parameter_property ADDR_W_IMEM DEFAULT_VALUE 12
set_parameter_property ADDR_W_IMEM DISPLAY_NAME ADDR_W_IMEM
set_parameter_property ADDR_W_IMEM TYPE INTEGER
set_parameter_property ADDR_W_IMEM ENABLED false
set_parameter_property ADDR_W_IMEM UNITS None
set_parameter_property ADDR_W_IMEM HDL_PARAMETER true
add_parameter CONTROL_WORD_W INTEGER 22
set_parameter_property CONTROL_WORD_W DEFAULT_VALUE 22
set_parameter_property CONTROL_WORD_W DISPLAY_NAME CONTROL_WORD_W
set_parameter_property CONTROL_WORD_W TYPE INTEGER
set_parameter_property CONTROL_WORD_W ENABLED false
set_parameter_property CONTROL_WORD_W UNITS None
set_parameter_property CONTROL_WORD_W HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset reset Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end disp_sel export Input 5
add_interface_port conduit_end display export Output 32
add_interface_port conduit_end av_writedata export Output 32


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_sink
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 0
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master av_address address Output 32
add_interface_port avalon_master av_readdata readdata Input 32
add_interface_port avalon_master av_writedata_reg writedata Output 32
add_interface_port avalon_master av_write_n write_n Output 1
add_interface_port avalon_master av_read_n read_n Output 1
add_interface_port avalon_master av_waitrequest waitrequest Input 1

